services:
  backend:
    container_name: kosmio_back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_APP_PORT}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - OVH_API_KEY=${OVH_API_KEY}
      - PYTHONPATH=/app/src/main
      - PYTHONUNBUFFERED=1
      - CHROMA_HOST=chroma_server 
      - CHROMA_PORT=8000
      - CHROMA_TOKEN=${CHROMA_TOKEN}
    depends_on:
      db:
        condition: service_started
      chroma_server:
        condition: service_started
    restart: on-failure
        
  db:
    image: postgres:15
    container_name: kosmio_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/service/bdd_service/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${BACKEND_DB_PORT}:5432"
      
  chroma_server:
    image: chromadb/chroma:latest
    container_name: kosmio_chroma
    volumes:
      - chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.token_authn.TokenAuthServerProvider
      - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_TOKEN}
    ports:
      - "${CHROMA_HOST_PORT}:8000"
    restart: unless-stopped

volumes:
  pgdata:
  chroma_data: