services:
  backend:
    container_name: kosmio_back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_APP_PORT}:8000"
    environment:
      # DB url,
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # OVH api key
      - OVH_API_KEY=${OVH_API_KEY}
      # Python module path. If you import a module, this is the root.
      - PYTHONPATH=/app/src/main
      # Force python to print everything right when it receive the print
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: kosmio_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/main/service/bdd_service/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${BACKEND_DB_PORT}:5433"
volumes:
  pgdata:
